#!/usr/bin/env bash

export CONTECO_LABEL="backup.package - ModEco"
export CONTECO_DESCRIPTION="Backup of all repositories of the package images of the ModEco ecosystem."

export CONTECO_TYPE="backup"
export CONTECO_NAME="package"
export CONTECO_TAG="20200428"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
